### ISSUE TITLE
Not filter method signature

### ISSUE THREAD

**Issue by elrhomariyounes** [supabase/postgrest-csharp#11]
# Feature request

## Is your feature request related to a problem? Please describe.

Hello, I was wondering for the Not filter if we can pass the QueryFilter parameters directly to the Not method instead of passing a QueryFilter object.

The current behavior we should do like this :

```csharp
var filter = new QueryFilter("username", Constants.Operator.Equals, "supabot");
var response = await client.Table<User>().Not(filter).Get();
```

## Describe the solution you'd like

To do the same thing as postgrest-js [not filter](https://github.com/supabase/postgrest-js/blob/master/src/lib/PostgrestFilterBuilder.ts#L41).

```csharp
var response = await client.Table<User>().Not("status",Constants.Operators.Equals,"ONLINE").Get();
```

Thank you.

**Comment by acupofjose** [comment]
Can do!
