### ISSUE TITLE
Chore: Unit Tests for Individual Filters

### ISSUE THREAD

**Issue by acupofjose** [supabase/postgrest-csharp#15]
# Chore

## Describe the chore

In the process of creating the `Not` shorthand methods, I've noticed that some of the filter requests are not necessarily being formed correctly. For instance, `contains` and `includes` while similar in functionality, require different request formatting.

Per filter tests will be required based off of: http://postgrest.org/en/v7.0.0/api.html#operators

**Comment by acupofjose** [comment]
Interestingly, attempting to use the `contains` operator gives me an error:

```
{
"hint": "No operator matches the given name and argument types. You might need to add explicit type casts.",
"details": null,
"code": "42883",
"message": "operator does not exist: text @> unknown"
}
```

As though `postgrest` doesn't know how to use it's own operator?

**Comment by elrhomariyounes** [comment]
@acupofjose We can close this for now all filters have tests, still to support some types in contains and contained filters as mentioned in #24
