### ISSUE TITLE
Filter method compilation error

### ISSUE THREAD

**Issue by elrhomariyounes** [supabase/postgrest-csharp#17]
# Bug report

## Describe the bug

Hello,

When trying to perform a filter request to check if a column value is null
```csharp
await client.Table<User>().Filter("data", Operator.Equals, null).Get();
```
A compilation error due to an ambiguity between Filter with string third parameter and List of objects overload

```csharp
public Table<T> Filter(string columnName, Operator op, List<object> criteria)
```

```csharp
public Table<T> Filter(string columnName, Operator op, string criteria)
```
## To Reproduce

1. Try to perform an Filter request to check if a column is null
```csharp
await client.Table<User>().Filter("data", Operator.Equals, null).Get();
```

**Comment by elrhomariyounes** [comment]
Hello @acupofjose, Any idea please ?

**Comment by acupofjose** [comment]
@elrhomariyounes sorry for the delay! I committed my solution for it onto master. Would you review as to whether it does what you expect?

Thank you!

**Comment by elrhomariyounes** [comment]
Yes thank you @acupofjose
