### ISSUE TITLE
Update a record not working

### ISSUE THREAD

**Issue by elrhomariyounes** [supabase/postgrest-csharp#2]
# Bug report

## Describe the bug

* Hello, while trying to update a record an Exception of type NullReferenceException.
After debugging the exception is thrown when calling the Update method in Builder class while initializing the QueryFilter object whit a null criteria the Helper method GetPropertyValue doesn't retrieve the value of the primary key property it returns null.
I figured it out instead of using the Helper method I used the PrimaryKeyValue Property of the model and worked perfectly. I submitted a PR :relaxed: for this case if is it ok.

* Second thing is when trying to update a non-existing user another exception is thrown of type JsonSerializationException. The issue is the Postgrest returns an empty array "[]" when trying to update a non-existing record and the Helper method MakeRequest when not a success status code is returned tries to deserialize the response content to an ErrorResponse object, an empty array cannot be deserialized to ErrorResponse.

Thank you.

## To Reproduce

1. Retrieve a user
```csharp
var user= await client.Builder<User>().Filter("username", Postgrest.Constants.Operator.Equals, "supabot").Single();
```
2. Update if not null
```csharp
user.Status = "OFFLINE";
await user.Update<User>();
```
3. To reproduce second case (Not Found user)
```csharp
var user = new User
{
   Username = "ghost",
   Status = "ONLINE"
};
await client.Builder<User>().Update(user);
```
## Expected behavior
1. User updated if not null
2. When trying to update a not existing user a RequestException to be thrown instead of JsonSerializationException

## System information

- OS: [Windows 10 Pro 1909]
- .Net core 3.1.x
- Visual Studio 16.8
- Version of supabase-postgrest-csharp: master branch of current repo

**Comment by acupofjose** [comment]
Expected Behavior #2 is fixed in commit [f51d8a6c](https://github.com/supabase/postgrest-csharp/commit/f51d8a6c58f76a1fdefd98e408d06660b91868f8)

Thanks again for a detailed bug report!
