### ISSUE TITLE
Stored procedure

### ISSUE THREAD

**Issue by elrhomariyounes** [supabase/postgrest-csharp#26]
# Feature request

## Is your feature request related to a problem? Please describe.

Hello, I saw in the PostgREST docs that we can call a **stored procedure**, I checked the [postgrest-js](https://github.com/supabase/postgrest-js/blob/master/src/PostgrestClient.ts#L51) repo and it's implemented.

I would love to work on it ☺️ 

## Describe the solution you'd like

* Call a stored procedure
```csharp
public Task<BaseResponse> Rpc(string procedureName, Dictionary<string, object> parameters);
```

## Questions

1. Should the method be called from **Table** object or **Client** ?

**Comment by acupofjose** [comment]
That would be great! Call from ‘Client’ as I believe procedures are agnostic of Table
