### ISSUE TITLE
Refactoring utils methods

### ISSUE THREAD

**Issue by elrhomariyounes** [supabase/postgrest-csharp#29]
# Chore

## Describe the chore

Hello @acupofjose, Your thoughts about moving utils methods in the Table class like (PrepareFilter, PrepareData, GenerateUrl)
to static methods in Helpers class and make it internal?

**Comment by acupofjose** [comment]
I sort of wrestled with this idea when I wrote `Table.cs` - it seems to me that `PrepareFilter`, `PrepareData`, and `GenerateUrl` are specific to, and will only be called by, the `Table` class. As such, I think it best to stay in where it is.

However - and this is just my own ignorance on proper testing - I made them public so as to be able to call them from the Testing project. Is there a way to make them internal and still testable?

**Comment by elrhomariyounes** [comment]
@acupofjose I think there is a way to do it, I will send a PR

**Comment by elrhomariyounes** [comment]
Solved in #30
