### ISSUE TITLE
BaseModel has default properties

### ISSUE THREAD

**Issue by elrhomariyounes** [supabase/postgrest-csharp#31]
# Bug report

## Describe the bug

Hello, To bind a Table to a Model we should inherit from BaseModel, I think we should remove the default properties like InsertedAt, UpdatedAt and Status 

## To Reproduce

1. Create a new table without the date timestamps (inserted_at, updated_at) and status
2. Create a model inherit from BaseModel

## Expected behavior

* Model without the extra properties (InsertedAt, UpdatedAt, Status)

Thank you very much

**Comment by acupofjose** [comment]
Agreed! Good call. Fixed in [75d67a5](https://github.com/supabase/postgrest-csharp/commit/75d67a56132e4d4cc03f98d781021c892a3a1203)
