### ISSUE TITLE
XML documentation comments

### ISSUE THREAD

**Issue by elrhomariyounes** [supabase/postgrest-csharp#5]
# Feature request

## Describe the solution you'd like

Hello, I was wondering if we can add XML documentation comments for methods and object properties to show up in the intellisense ?

Thank you.

**Comment by acupofjose** [comment]
Yessir! Good idea. It's a solid amount of code to comment, so I'm working on it, but it'll be a little whilte!

**Comment by elrhomariyounes** [comment]
@acupofjose Thank you very much, I would be glad to help

**Comment by acupofjose** [comment]
See the latest commit for comments on most of the codebase!

**Comment by elrhomariyounes** [comment]
Awesome!, thank you @acupofjose

**Comment by acupofjose** [comment]
I've also added a `docfx` generation action that creates a documentation website for this project. You can find it on the readme!
