### ISSUE TITLE
Range request not working

### ISSUE THREAD

**Issue by elrhomariyounes** [supabase/postgrest-csharp#8]
# Bug report

## Describe the bug

Hello, while trying to perform a **Range request** an exception is thrown as described in the StackTrace below
```
StackTrace" at 
System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)\r\n   at
System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)\r\n   at System.Net.Http.Headers.HttpHeaders.Add(String name, String value)\r\n   at 
Postgrest.Helpers.<MakeRequest>d__5.MoveNext() 
```
After debugging I found that issue is when performing a **Range request with from parameter only or both from and to** the headers expected by Postgrest are :
* Range-Unit : items
* Content-Range : 1-3 (we suppose 1 is the from parameter and 3 is to)

The second header will throw the exception when trying to add it to the **HttpRequestMessage.Headers** because is not a valid one
[Exception line](https://github.com/supabase/postgrest-csharp/blob/master/Postgrest/Helpers.cs#L72)

## To Reproduce

1. Perform a Range request
```csharp
var response = await client.Builder<User>().Range(2).Get();
```

## Expected behavior

* Get a response with the requested size

## System information

-OS: [Windows 10 Pro 1909]
-.Net core 3.1.x
-Visual Studio 16.8
-Version of supabase-postgrest-csharp: master branch of current repo

**Comment by acupofjose** [comment]
@elrhomariyounes - thank you for all your hard work on these bug reports! Would you be interested in being a contributor on this Repo?

**Comment by elrhomariyounes** [comment]
Hi, always a pleasure to contribute. Sure thank you very much @acupofjose
